/** Compact native layout. Preserve the original category and custom colour tokens. */
export const VISUAL_CSS = String.raw`
.dp-root{ --dsw-alias-label-primary:#242424;--dsw-alias-label-secondary:#666;--dsw-alias-label-tertiary:#8a8a8a;--dsw-alias-bg-base:#fff;--dsw-alias-bg-layer-1:#fff;--dsw-alias-bg-layer-2:#f4f5f6;--dsw-alias-bg-layer-3:#fff;--dsw-alias-border-l2:#e5e7eb;--dsw-alias-border-l3:#e5e7eb;--dsw-alias-border-primary:#e5e7eb;--dsw-alias-state-business-primary:#333;--dsw-alias-interactive-bg-hover:#f4f5f6;--dsw-alias-interactive-bg-active:#e9ebee;--dp-grid-label:116px}
body[data-ds-dark-theme] .dp-root{--dsw-alias-label-primary:#eee;--dsw-alias-label-secondary:#bbb;--dsw-alias-label-tertiary:#999;--dsw-alias-bg-base:#242424;--dsw-alias-bg-layer-1:#2b2b2b;--dsw-alias-bg-layer-2:#333;--dsw-alias-bg-layer-3:#333;--dsw-alias-border-l2:#444;--dsw-alias-border-l3:#444;--dsw-alias-border-primary:#444;--dsw-alias-interactive-bg-hover:#333;--dsw-alias-interactive-bg-active:#444;--dsw-alias-state-business-primary:#ccc}
.dp-main{display:flex;flex-direction:column;flex:1;min-height:0;min-width:0}
.dp-topbar{flex-basis:56px;padding:0 20px;gap:12px;border-bottom:1px solid var(--dsw-alias-border-l2)}.dp-topbar-title{font-size:14px;letter-spacing:-.3px;white-space:nowrap}.dp-topbar-path{display:none}.dp-shell-back,.dp-shell-refresh{width:28px;padding:0}.dp-status{font-size:11px;white-space:nowrap}.dp-shell-today{font-size:11px}
.dp-sidebar{display:flex;align-items:center;gap:24px;padding:0 16px;border:0;flex:1;min-width:0;overflow-x:auto}
.dp-nav{border:0;padding:0;flex:1;gap:18px;min-width:max-content}.dp-nav-item{height:56px;padding:0 2px;font-size:13px;position:relative;border-radius:0;color:var(--dsw-alias-label-secondary)}
.dp-sidebar>.dp-btn{flex-shrink:0}.dp-nav-item[aria-selected=true]{background:transparent;color:var(--dsw-alias-label-primary);font-weight:600}.dp-nav-item[aria-selected=true]:after{content:"";position:absolute;height:2px;background:currentColor;bottom:0;left:2px;right:2px;border-radius:2px}.dp-nav-item:hover{background:transparent;color:var(--dsw-alias-label-primary)}.dp-agent-trigger{border:1px solid var(--dsw-alias-border-l2);background:transparent;border-radius:20px;padding:0 12px;height:30px;color:var(--dsw-alias-label-primary)}
.dp-page{animation:none;padding:18px 24px 20px;max-width:1440px;width:100%}.dp-head{margin-bottom:16px;gap:8px;min-height:30px;flex-wrap:wrap;flex-shrink:0}
.dp-head-copy{display:flex;align-items:baseline;gap:10px;min-width:0}.dp-head-copy h2{font-size:18px;line-height:1.4;font-weight:600}.dp-head-copy>.dp-muted{font-size:12px}
.dp-head-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.dp-btn{height:29px;font-size:13px}.dp-btn--sm{height:26px;font-size:12px}
.dp-section-head{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px}.dp-section-head h3{font-size:13px;font-weight:500}.dp-tag,.dp-category{font-size:11px;color:var(--dsw-alias-label-secondary)}
/* Daily agenda: times outside the coloured item, no dashboard tiles. */
.dp-root[data-page=today] .dp-page{max-width:1100px;padding-top:24px}.dp-root[data-page=today] .dp-head{margin-bottom:22px}.dp-root[data-page=today] .dp-head-copy h2{font-size:23px;letter-spacing:-.5px}.dp-root[data-page=today] .dp-head-copy>.dp-muted{font-size:12px}.dp-dashboard{display:block}.dp-agenda{border:0;padding:0;background:transparent}.dp-tl{display:flex;flex-direction:column;gap:6px}
.dp-agenda-row{display:flex;gap:12px;align-items:center;min-height:52px;padding:8px 12px 8px 0;border:0;border-radius:0;background:transparent;color:var(--dsw-alias-label-primary);position:relative;isolation:isolate}.dp-agenda-row:after{content:"";position:absolute;left:66px;right:0;top:0;bottom:0;border-radius:6px;background:var(--dp-accent-soft,var(--dp-study-soft));z-index:-1}.dp-agenda-row:before{content:"";position:absolute;width:3px;left:66px;top:9px;bottom:9px;border-radius:2px;background:var(--dp-accent,var(--dp-study));z-index:0}.dp-agenda-row.is-next{background:transparent}.dp-agenda-row.is-next .dp-agenda-time b{font-weight:650;color:var(--dsw-alias-label-primary)}.dp-agenda-row.is-next .dp-agenda-copy>b:after{content:"接下来";font-size:10px;font-weight:400;margin-left:10px;color:var(--dsw-alias-label-tertiary)}.dp-agenda-row.is-done{opacity:.5}.dp-agenda-row.is-done .dp-agenda-copy>b{text-decoration:line-through}.dp-agenda-row .dp-check{width:18px;height:18px;border-radius:4px;flex-shrink:0;border-color:#bcc7d1;margin-left:12px}
.dp-agenda-time{display:flex;flex-direction:column;flex:0 0 54px;line-height:1.4;font-size:13px;color:var(--dsw-alias-label-secondary)}.dp-agenda-time b{font-weight:450}.dp-agenda-time small{font-size:10px;color:var(--dsw-alias-label-tertiary)}
.dp-agenda-copy{display:flex;align-items:baseline;gap:12px;flex:1;min-width:0}.dp-agenda-copy>b{font-size:15px;font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}.dp-agenda-copy>p{font-size:11px;color:var(--dsw-alias-label-secondary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}.dp-agent-source{font-size:10px;color:var(--dsw-alias-label-secondary);display:flex;align-items:center;gap:3px;white-space:nowrap}.dp-agenda-row .dp-category{font-size:10px;color:var(--dsw-alias-label-secondary)}
.dp-agenda-add{margin-top:7px;margin-left:66px;min-height:28px;width:auto;border:0;color:var(--dsw-alias-label-tertiary);font-size:12px;justify-content:flex-start}.dp-due-notice{display:flex;gap:7px;align-items:center;font-size:12px;padding:6px 0;color:var(--dp-activity-ink)}
.dp-agent-inline{display:flex;align-items:center;gap:10px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;padding:10px 12px;margin-top:22px;background:var(--dsw-alias-bg-base)}.dp-agent-inline>svg{flex-shrink:0;color:var(--dsw-alias-label-secondary)}.dp-agent-inline textarea{border:0;resize:none;flex:1;min-width:0;background:transparent;padding:0;line-height:1.6;font-size:13px;max-height:120px}.dp-agent-inline textarea:focus-visible{outline:0}.dp-agent-inline:focus-within{border-color:#a0a4ab;box-shadow:0 0 0 2px rgb(0 0 0/.03)}.dp-agent-inline>.dp-btn{flex-shrink:0;height:30px;font-size:12px;border-radius:7px}.dp-agent-inline textarea::placeholder{color:var(--dsw-alias-label-tertiary)}
.dp-agent-activity{font-size:11px;margin-top:12px;color:var(--dsw-alias-label-secondary)}.dp-agent-activity-head{display:flex;align-items:center;gap:6px}.dp-agent-activity-head b{font-weight:500;color:var(--dsw-alias-label-primary)}.dp-agent-activity-head small{font-size:10px;color:var(--dsw-alias-label-tertiary)}.dp-agent-activity-head button{display:flex;align-items:center;gap:3px;font-size:10px}.dp-agent-activity-lines{display:flex;gap:4px 18px;flex-wrap:wrap;margin:4px 0 0 20px}.dp-agent-activity-lines p{display:flex;gap:4px;align-items:center;font-size:10px}.dp-agent-activity>p{margin:4px 0 0 20px;font-size:10px}
.dp-root[data-page=week] .dp-body,.dp-root[data-page=gym] .dp-body{overflow:hidden}
.dp-root:is([data-page=week],[data-page=gym]) [role=tabpanel]{height:100%;min-height:0}
.dp-root:is([data-page=week],[data-page=gym]) .dp-page{display:flex;flex-direction:column;height:100%;min-height:0}
.dp-week{flex:1;min-height:0;grid-template-columns:195px minmax(0,1fr);gap:14px;align-items:stretch}
.dp-pool{max-height:none;min-height:0}.dp-grid-scroll{display:flex;flex-direction:column;height:100%;min-height:0;max-height:none;overflow:hidden}
.dp-grid-head{flex-shrink:0;position:static;min-height:31px;align-items:center}.dp-grid{flex:1;min-height:0;grid-auto-rows:unset;gap:2px}
.dp-grid-period{font-size:10px;line-height:1;gap:4px;padding-right:5px;white-space:nowrap}.dp-grid-period small{display:none}
.dp-gblock{min-height:0;overflow:hidden}.dp-gblock.is-locked{background:var(--dp-accent-soft,var(--dp-study-soft));border-left-style:solid}.dp-gblock[data-adaptive=true]{border-style:solid;border-width:0 0 0 3px;outline:1px dashed color-mix(in srgb,var(--dp-accent,var(--dp-study)) 55%,transparent);outline-offset:-1px}.dp-gblock-body{padding:3px 6px;min-height:0}.dp-gblock-title{font-size:11px;line-height:1.25;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden;white-space:normal}.dp-gblock-note,.dp-gblock-gym{font-size:10px;line-height:1.25}.dp-holiday{font-size:9px;font-style:normal;display:block;color:#d97706;line-height:1.2}
.dp-grid-day small{font-size:10px}.dp-cell{min-height:0}.dp-grid-corner{font-size:10px}
.dp-gym{flex:1;min-height:0;grid-template-columns:210px minmax(0,1fr);align-items:stretch;gap:16px}
.dp-gym-lib,.dp-gym-session{max-height:none;min-height:0;height:100%}.dp-gym-row{min-height:36px;padding:5px 8px;border-color:var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1)}.dp-log-set{font-size:11px;color:#666;border:1px solid #e5e7eb;padding:2px 6px;white-space:nowrap}.dp-exercise-card{flex-shrink:0;animation:dp-row-in .23s ease-out}
.dp-gym-slot{height:7px}.dp-gym-session[data-dragging=true] .dp-gym-slot{height:14px}.dp-gym-session[data-dragging=true] .dp-gym-slot[data-preview=true]{height:28px;border:1px dashed var(--dp-gym);background:var(--dp-gym-soft)}
.dp-gym-session[data-dragging=true]{background:color-mix(in srgb,var(--dp-gym-soft) 25%,transparent);outline:1px dashed var(--dp-gym);outline-offset:3px}.dp-gym-slot-label{color:var(--dp-gym-ink)}
.dp-actual-sets{padding:2px 8px 2px 30px;font-size:11px}.dp-actual-sets[open]{padding-bottom:8px}.dp-actual-sets>summary{padding:1px 0;color:var(--dsw-alias-label-secondary)}
.dp-training-history{margin-top:12px;border-top:1px solid var(--dsw-alias-border-l2);padding-top:8px;font-size:12px;flex-shrink:0}.dp-training-history>summary{cursor:pointer;color:var(--dsw-alias-label-secondary)}.dp-gym-trends{margin-top:8px;font-size:12px}.dp-set-form input,.dp-set-form select{font-size:12px;padding:4px 6px}
@keyframes dp-row-in{from{opacity:.3;transform:translateY(-6px)}to{opacity:1;transform:translateY(0)}}
.dp-root[data-page=learn] .dp-body{overflow:hidden}.dp-root[data-page=learn] [role=tabpanel]{height:100%;min-height:0}.dp-root[data-page=learn] .dp-page{display:flex;flex-direction:column;height:100%;min-height:0}.dp-learn{flex:1;min-height:0;grid-template-rows:auto minmax(0,1fr);max-width:none;gap:16px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}.dp-week-stats{border-radius:6px;grid-column:1/-1;padding:10px 12px;display:grid;grid-template-columns:auto minmax(0,1fr);gap:8px 24px;align-items:center}.dp-week-stats-row{margin-bottom:0;gap:24px}.dp-big b{font-size:20px}.dp-week-bar-track{height:40px}.dp-learn-legend{margin-top:0;grid-column:2}.dp-learn-col{gap:7px;min-height:0;max-height:100%;overflow:auto;padding-right:3px}.dp-learn-card{padding:9px 11px;border-radius:6px}.dp-learn-col:first-of-type .dp-learn-card{border-left-color:var(--dp-study)}.dp-learn-col:last-of-type .dp-learn-card{border-left-color:var(--dp-gym)}.dp-book-emblem{display:none}
.dp-review-path{display:none}.dp-journal-archive{margin:0}.dp-workflow-disclosure>summary{padding-top:0}
.dp-coach-overlay{position:absolute;inset:0;z-index:20;display:flex;align-items:center;justify-content:center;background:rgb(0 0 0/.12);padding:16px}.dp-coach-overlay[hidden]{display:none}
.dp-coach-drawer{width:min(600px,100%);max-height:calc(100% - 12px);overflow:auto;background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);box-shadow:var(--dp-shadow-float);border-radius:12px;padding:18px 22px}
.dp-coach-drawer>header{display:flex;align-items:center;gap:10px;padding-bottom:16px;margin-bottom:12px;font-size:15px}.dp-coach-drawer>header>div{display:flex;flex-direction:column;gap:3px}.dp-coach-drawer>header small{display:none}.dp-coach-drawer>header label{font-size:10px;color:var(--dsw-alias-label-secondary)}.dp-coach-drawer>header input{font-size:11px;padding:3px 5px}
.dp-training-records{display:flex;flex-direction:column;gap:12px}.dp-record-exercise{border-bottom:1px solid #e5e7eb;padding:8px 0;font-size:13px}.dp-record-exercise .dp-actual-sets{padding-left:0}.dp-agent-receipt{display:flex;gap:16px;flex-wrap:wrap;margin:12px 0}.dp-agent-receipt span{font-size:11px;color:var(--dsw-alias-label-secondary)}.dp-agent-receipt span:first-child{font-weight:600;color:var(--dsw-alias-label-primary)}.dp-workflow{padding:0;border:0;background:transparent;margin:0;gap:12px}.dp-workflow-head{display:none}.dp-coach-modes{display:flex;gap:20px;flex-wrap:wrap;margin-bottom:12px;border-bottom:1px solid var(--dsw-alias-border-l2)}.dp-coach-modes button{padding:6px 1px 9px;font-size:12px;border-radius:0;background:transparent;color:var(--dsw-alias-label-secondary);border-bottom:2px solid transparent}.dp-coach-modes button[aria-pressed=true]{background:transparent;color:var(--dsw-alias-label-primary);border-bottom-color:currentColor;font-weight:600;outline:0}
.dp-range-options{font-size:10px;color:var(--dsw-alias-label-tertiary);margin-bottom:10px}.dp-range-options>summary{display:flex;align-items:center;justify-content:space-between;cursor:pointer;list-style:none}.dp-range-options>summary span{display:flex;gap:4px;align-items:center}.dp-range-options>.dp-review-range{margin-top:8px}.dp-range-options[open]>summary{margin-bottom:5px}
.dp-future-range{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:10px;font-size:11px;color:var(--dsw-alias-label-secondary)}.dp-future-range select,.dp-future-range input{font-size:11px;padding:4px 6px;max-width:140px;background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:5px}.dp-coach-drawer>header label[hidden]{display:none}
.dp-replace-option{display:flex;align-items:center;gap:6px}.dp-replace-option input{width:12px;height:12px;margin:0;accent-color:#333}
.dp-draft-editor-hint{font-size:11px;color:var(--dsw-alias-label-tertiary);margin-bottom:8px}.dp-draft-edit-row{display:flex;flex-wrap:wrap;align-items:center;gap:5px 8px;padding:8px 0;border-bottom:1px solid var(--dsw-alias-border-l2)}.dp-draft-edit-row input{font-size:12px;padding:4px 6px;border:1px solid var(--dsw-alias-border-l2);border-radius:4px;background:var(--dsw-alias-bg-base);min-width:0}.dp-draft-edit-title{flex:1 1 140px;font-weight:500}.dp-draft-edit-time{display:flex;align-items:center;gap:4px;flex-wrap:wrap;font-size:10px;color:var(--dsw-alias-label-secondary)}.dp-draft-edit-time input[type=date]{width:114px}.dp-draft-edit-time input[type=time]{width:83px}.dp-draft-edit-time button{font-size:10px;padding:3px;color:var(--dsw-alias-label-secondary)}.dp-draft-edit-note{flex-basis:100%;border-color:transparent!important;font-size:11px!important}.dp-draft-edit-note:focus{border-color:var(--dsw-alias-border-l2)!important}.dp-draft-edit-row small{font-size:10px;color:var(--dsw-alias-label-secondary)}
.dp-coach-compose[hidden]{display:none}.dp-review-source{font-size:11px;color:var(--dsw-alias-label-secondary);padding:8px 12px;background:var(--dsw-alias-bg-layer-2);border-radius:7px}.dp-review-source>span{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:1;overflow:hidden;line-height:1.7}.dp-review-source>div{display:flex;justify-content:flex-end;gap:16px;margin-top:6px;font-size:10px}.dp-review-source button{display:flex;gap:3px;align-items:center}.dp-change-preview{font-size:12px;line-height:1.65}
.dp-coach-drawer textarea:focus-visible{outline:0;border-color:#9da2aa;box-shadow:0 0 0 2px rgb(0 0 0/.04)}
.dp-workflow-focus{font-size:12px;display:flex;gap:5px;align-items:center;margin-bottom:8px}.dp-review-range{display:flex;gap:8px;align-items:center;font-size:11px;color:var(--dsw-alias-label-secondary);margin-bottom:8px}.dp-review-range select,.dp-review-range input{font-size:11px;padding:3px 6px}
.dp-composer textarea{display:block;width:100%;min-height:190px;max-height:320px;font-size:14px;line-height:1.75;padding:12px 14px;resize:vertical}.dp-composer-foot{display:flex;justify-content:space-between;align-items:center;font-size:10px;color:var(--dsw-alias-label-tertiary);padding:4px 0}.dp-composer-foot span{display:flex;align-items:center;gap:5px}
.dp-coach-actions{display:flex;gap:8px;margin:8px 0}.dp-coach-actions .dp-btn:not(.dp-btn--primary){border-color:transparent;color:var(--dsw-alias-label-secondary)}.dp-coach-note{font-size:10px;color:var(--dsw-alias-label-tertiary)}.dp-coach-output:not(:has(.dp-coach-steps)){border-top:1px solid var(--dsw-alias-border-l2);padding-top:14px;margin-top:14px}
.dp-coach-output .dp-section-head{margin:0}.dp-coach-output:has(.dp-coach-steps){display:none}.dp-coach-output .dp-section-head h3{font-size:14px}.dp-eyebrow{display:none}
.dp-coach-steps{display:none}.dp-feedback-stamp{font-size:10px;color:var(--dsw-alias-label-tertiary)}.dp-agent-summary{font-size:13px;margin:5px 0!important}.dp-result-section{font-size:12px;margin:8px 0}.dp-result-section>summary{display:flex;gap:5px;align-items:center;cursor:pointer}.dp-change-list{padding:5px 0}.dp-change-list>div{display:flex;gap:6px;align-items:center;padding:2px 0}.dp-change-list svg{color:var(--dp-gym);flex-shrink:0}
.dp-memory-item{padding:4px 0}.dp-memory-item small{display:block}.dp-result-links{display:flex;gap:12px;flex-wrap:wrap;margin-top:12px}.dp-result-links button{display:flex;gap:4px;align-items:center;font-size:11px;color:var(--dsw-alias-label-primary)}.dp-coach-context{font-size:10px;margin-top:8px;color:var(--dsw-alias-label-tertiary)}.dp-coach-context>summary{cursor:pointer}.dp-coach-footer{display:flex;align-items:center;justify-content:space-between;font-size:10px;color:var(--dsw-alias-label-tertiary);margin-top:10px}.dp-coach-footer button{display:flex;gap:4px;align-items:center}.dp-feedback-questions{font-size:12px}.dp-allocation{font-size:12px;display:flex;gap:7px;margin-top:8px}.dp-draft-changes{font-size:12px}.dp-draft-changes>.dp-btn{margin-top:8px}
.dp-page-menu{position:relative;font-size:12px}.dp-page-menu>summary{display:flex;align-items:center;gap:4px;padding:5px 7px;cursor:pointer;color:var(--dsw-alias-label-secondary);list-style:none;border-radius:5px}.dp-page-menu>div{position:absolute;right:0;top:100%;z-index:6;padding:5px;min-width:160px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-base);box-shadow:var(--dp-shadow-float)}.dp-page-menu .dp-btn{display:flex;border:0;width:100%;justify-content:flex-start;background:transparent}.dp-pool{border-right:1px solid var(--dsw-alias-border-l2);padding-right:14px}.dp-pool-head{font-size:13px;font-weight:500}.dp-pool .dp-faint{font-size:11px}.dp-gym-row{border-radius:5px}.dp-exercise-card{border-radius:5px}.dp-week-stats{border:0;border-radius:0;border-bottom:1px solid var(--dsw-alias-border-l2);padding:0 0 16px}.dp-learn-card{border:0;border-bottom:1px solid var(--dsw-alias-border-l2);border-radius:0;border-left:3px solid var(--dp-accent,var(--dp-study));background:transparent}.dp-learn-col>.dp-subhead{font-size:13px}.dp-learn-col>.dp-subhead>.dp-faint{display:none}
.dp-holiday-settings{display:flex;gap:8px;align-items:center;flex-wrap:wrap;font-size:12px}.dp-holiday-settings input,.dp-holiday-settings select{font-size:12px}.dp-holiday-settings a{color:var(--dp-study)}
/* Fixed workspace: the composer, plan and actions keep their position. */
.dp-coach-output[hidden]{display:none!important}
.dp-coach-drawer:has(.dp-workflow--workspace){height:min(680px,calc(100% - 12px));display:flex;flex-direction:column;overflow:hidden;width:min(660px,100%);padding:18px 22px}
.dp-coach-drawer:has(.dp-workflow--workspace)>header{flex-shrink:0;margin-bottom:10px;padding-bottom:6px;min-height:30px}
.dp-workflow--workspace{flex:1;min-height:0;gap:12px;margin:0}
.dp-workflow--workspace .dp-coach-compose{flex-shrink:0}.dp-workflow--workspace .dp-composer textarea{height:148px;min-height:148px;max-height:148px;resize:none;font-size:13px;line-height:1.7}
.dp-workflow--workspace .dp-coach-modes{margin-bottom:10px}.dp-workflow--workspace .dp-workflow-focus{display:none}.dp-workflow--workspace .dp-range-options,.dp-workflow--workspace .dp-future-range,.dp-workflow--workspace .dp-review-range{min-height:26px;margin-bottom:8px}
.dp-workflow--workspace .dp-replace-option{margin:5px 0 0;font-size:10px}
.dp-agent-plan{display:flex;flex-direction:column;flex:1;min-height:0;border-top:1px solid var(--dsw-alias-border-l2);padding-top:8px}.dp-agent-plan-head{display:flex;align-items:center;gap:10px;flex-shrink:0;height:30px}.dp-agent-plan-head>b{font-size:12px;font-weight:550}.dp-agent-plan-head>span{font-size:10px;color:var(--dsw-alias-label-tertiary)}.dp-agent-plan-head>.dp-btn{margin-left:auto;font-size:11px}
.dp-agent-plan-scroll{flex:1;min-height:0;overflow:auto;overscroll-behavior:contain;padding-right:3px;scrollbar-gutter:stable}
.dp-agent-plan-empty{color:var(--dsw-alias-label-tertiary);font-size:12px;text-align:center;margin:20px 0;line-height:1.8}.dp-agent-plan-empty>svg{margin:auto}.dp-agent-plan-empty small{font-size:11px}.dp-agent-plan-detail{font-size:11px;color:var(--dsw-alias-label-secondary);margin:10px 0}.dp-agent-plan-detail>summary{display:flex;gap:4px;align-items:center;cursor:pointer}.dp-agent-plan-detail p{line-height:1.65;margin:5px 0}.dp-agent-plan-questions{font-size:11px;line-height:1.7;color:var(--dsw-alias-label-secondary);margin-top:10px}
.dp-agent-workspace-footer{flex-shrink:0;border-top:1px solid var(--dsw-alias-border-l2);padding-top:8px}.dp-agent-workspace-status{font-size:10px;color:var(--dsw-alias-label-tertiary);height:29px;overflow:auto;line-height:1.4}.dp-agent-workspace-status[role=alert]{color:#b91c1c}.dp-agent-workspace-actions{display:grid;grid-template-columns:1.25fr 1fr 1fr;gap:8px}.dp-agent-workspace-actions>.dp-btn{width:100%;height:32px;font-size:12px}
.dp-workflow--workspace .dp-draft-edit-title{flex-basis:180px}.dp-workflow--workspace .dp-draft-edit-row{gap:4px 6px;padding:6px 0}.dp-workflow--workspace .dp-draft-edit-note{padding:2px 6px}.dp-workflow--workspace input:disabled{opacity:1;color:var(--dsw-alias-label-secondary);background:transparent}
@media(max-width:480px){.dp-coach-drawer:has(.dp-workflow--workspace){padding:12px}.dp-workflow--workspace .dp-coach-modes{gap:14px}.dp-workflow--workspace .dp-composer textarea{height:132px;min-height:132px;max-height:132px}.dp-agent-workspace-actions{gap:5px}.dp-agent-workspace-actions>.dp-btn{font-size:11px}.dp-workflow--workspace .dp-draft-edit-title{flex-basis:100%}}
.dp-coach-output:has(.dp-agent-brief){margin:0;padding:0;border:0}.dp-coach-drawer:has(.dp-agent-brief)>header{margin-bottom:6px;padding-bottom:8px}
.dp-brief-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:4px 0 22px}.dp-brief-title h3{font-size:21px;line-height:1.4;font-weight:600;letter-spacing:-.4px}.dp-brief-title>span{display:flex;align-items:center;gap:5px;font-size:10px;color:var(--dsw-alias-label-tertiary)}.dp-brief-title i{width:5px;height:5px;border-radius:50%;background:var(--dp-gym)}
.dp-brief-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:26px}.dp-brief-columns>section+section{border-left:1px solid var(--dsw-alias-border-l2);padding-left:24px}.dp-brief-columns h4{font-size:11px;font-weight:400;color:var(--dsw-alias-label-tertiary);margin-bottom:6px}.dp-brief-items{display:flex;flex-direction:column;gap:4px}.dp-brief-items>button{display:flex;align-items:center;justify-content:space-between;gap:8px;text-align:left;min-height:44px;width:100%;border-radius:5px;padding:4px 0}.dp-brief-items>button:hover{background:var(--dsw-alias-interactive-bg-hover)}.dp-brief-items b{display:block;font-size:14px;line-height:1.45;font-weight:500;overflow-wrap:anywhere}.dp-brief-items small{display:block;font-size:10px;line-height:1.6;color:var(--dsw-alias-label-tertiary);margin-top:1px}.dp-brief-items svg{flex-shrink:0;opacity:.3}.dp-brief-items>button:hover svg{opacity:1}.dp-brief-items>p{font-size:12px;line-height:1.7;margin-top:8px}
.dp-brief-memory{display:flex;gap:14px;align-items:baseline;margin-top:18px;padding-top:12px;border-top:1px solid var(--dsw-alias-border-l2);font-size:12px}.dp-brief-memory>span{color:var(--dsw-alias-label-tertiary);font-size:11px;white-space:nowrap}.dp-brief-memory>button{display:flex;gap:6px;align-items:center;text-align:left}.dp-brief-memory svg{opacity:.35;flex-shrink:0}
.dp-brief-actions{display:flex;gap:8px;align-items:center;margin-top:20px}.dp-brief-actions .dp-btn{height:32px;font-size:12px}.dp-brief-audit{margin-top:14px;font-size:11px;color:var(--dsw-alias-label-secondary)}.dp-brief-audit>summary{display:flex;align-items:center;gap:5px;list-style:none;cursor:pointer;font-size:10px;color:var(--dsw-alias-label-tertiary)}.dp-brief-audit[open]>summary{margin-bottom:10px}.dp-brief-audit p{margin:6px 0;line-height:1.8}.dp-brief-original{white-space:pre-wrap;padding:8px 10px;background:var(--dsw-alias-bg-layer-2);border-radius:5px}.dp-brief-questions{font-size:12px;margin-top:16px;line-height:1.7}.dp-brief-questions>b{font-weight:500}.dp-brief-warning{font-size:12px;line-height:1.7;color:#b45309;margin-top:10px}
@media(max-width:480px){.dp-brief-columns{grid-template-columns:1fr;gap:18px}.dp-brief-columns>section+section{border-left:0;padding-left:0;border-top:1px solid var(--dsw-alias-border-l2);padding-top:12px}}
@media(max-height:760px){.dp-root[data-page=today] .dp-page{padding-top:18px}.dp-root[data-page=today] .dp-head{margin-bottom:16px}.dp-agenda-row{min-height:46px;padding-top:6px;padding-bottom:6px}.dp-agent-inline{margin-top:16px;padding:8px 10px}}
@media(max-width:1050px){.dp-topbar{gap:8px;padding:0 12px}.dp-sidebar{padding:0 12px;gap:16px}.dp-nav{gap:14px}.dp-status,.dp-shell-today{display:none}}
@media(max-width:850px){.dp-page{padding:10px 12px}.dp-head-copy{flex-wrap:wrap;gap:4px 8px}.dp-week{grid-template-columns:155px minmax(0,1fr);gap:8px}.dp-root{--dp-grid-label:96px}.dp-grid-period{font-size:9px}.dp-grid-period b{display:none}.dp-gym{grid-template-columns:180px minmax(0,1fr)}.dp-agenda-copy{display:block}.dp-agenda-copy>p{font-size:10px}.dp-week-stats{grid-template-columns:1fr}.dp-learn-legend{grid-column:1}.dp-head-actions{gap:4px}.dp-topbar-title{display:none}.dp-nav{gap:10px}.dp-nav-item{font-size:12px}.dp-sidebar{padding:0;gap:12px}.dp-agent-trigger{font-size:11px}}
@media(max-width:600px){.dp-status{display:none}.dp-sidebar{padding:4px 8px}.dp-nav-item{padding:0 8px}.dp-root[data-page=learn] .dp-body{overflow:auto}.dp-root[data-page=learn] .dp-page{height:auto}.dp-learn{grid-template-columns:1fr;grid-template-rows:auto}.dp-week-stats{grid-column:1}.dp-week{grid-template-columns:1fr}.dp-pool{max-height:90px;min-height:0}.dp-grid-scroll{min-height:360px}.dp-root[data-page=week] .dp-body{overflow:auto}.dp-gym{grid-template-columns:140px minmax(0,1fr);gap:8px}.dp-gym-row{flex-wrap:wrap}.dp-gym-name{flex-basis:70%}.dp-head-copy>.dp-muted{display:none}.dp-coach-drawer{padding:12px}.dp-coach-drawer>header{flex-wrap:wrap}.dp-agenda-copy>p{max-width:180px}}
`
